# Generated by Django 5.1 on 2024-08-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('profileImg', models.ImageField(blank=True, null=True, upload_to='profileimg')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
